excerpt_separator: <!--more-->
highlighter: rouge
markdown: kramdown
url: http://linguisht.github.io
baseurl: http://linguisht.github.io/
title: Linguisht
tagline: Language and technology
description: "Language, technology, the business around it. My points of view."
paginate: 5
