excerpt_separator: <!--more-->
highlighter: pygments
markdown: kramdown
url: http://langustry.com
baseurl: http://langustry.com/
title: Langustry
tagline: Language industry observations
description: "With 20+ years in the language industry, I still learn something new every day. Here I share."
paginate: 5