excerpt_separator: ""
highlighter: pygments
markdown: kramdown
url: http://Linguisht.github.io
title: Langustry
tagline: Language industry thoughts and observations
description: My observations on the language industry. With 20+ years experience, I still learn something new every day. Here I share.
paginate: 5