excerpt_separator: <!--more-->
highlighter: pygments
markdown: kramdown
url: http://langustry.com
baseurl: http://langustry.com/
title: Langustry
tagline: Language industry personal points of view
description: "Lanugage, technology, the business around it. My points of view on language industry stuff."
paginate: 5