excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://Linguisht.github.io
title: Langustry
tagline: Language industry ideas and observations
description: With 20+ years in the language industry, I still learn something new every day. This is a place for me to share and, in so doing, learn even more.
paginate: 5